name: discordconnectionAcrom
version: '1.0'
main: com.monkey.discordconnectionAcrom.DiscordConnectionAcrom
api-version: '1.20'
authors: [ MonkeyMoon104 ]

commands:
  discord-connection:
    description: Connettiti con il tuo account discord
    usage: /discord-connection